#!/usr/bin/env ruby
#Reset Presence Script
#@author Aldo

require 'logger'
require 'rest_client'

path = "/var/log/ejabberd/scripts.log"
file = File.open(path, File::WRONLY | File::APPEND | File::CREAT)
file.sync = true
$logger = Logger.new(file)
$logger.level = Logger::DEBUG

def getOption(option)
  File.open('/etc/ejabberd/ssconfig.cfg', 'r') do |f1|  
    while line = f1.gets  
      line = line.gsub(/\n/,'')
      if line.match(/^#/)
        #Comments
      elsif line.match(/^#{option}/)
        return line.gsub(/#{option}/,'')
      end  
    end  
  end
  return "Undefined"
end

$url = getOption("reset_presence_api=")


def log(text)
	$logger.info "Reset Presence Script: " + text
end


def resetPresence()
  begin
    RestClient.post($url, :password => "pass")
    return true
  rescue => e
    log("#{e.class.name}: #{e.message}")
    return false
  end
end

if (resetPresence())
  puts "Reset Presence [OK]"
  log( "Reset Presence [OK]" )
else
  puts "Reset Presence [FAIL]"
  log( "Reset Presence [FAIL]" )
end


