#!/usr/bin/env ruby
#Unset Presence Script
#@author Aldo

require 'logger'
require 'rest_client'

path = "/var/log/ejabberd/scripts.log"
file = File.open(path, File::WRONLY | File::APPEND | File::CREAT)
file.sync = true
$logger = Logger.new(file)
$logger.level = Logger::DEBUG

def getOption(option)
  File.open('/etc/ejabberd/ssconfig.cfg', 'r') do |f1|  
    while line = f1.gets  
      line = line.gsub(/\n/,'')
      if line.match(/^#/)
        #Comments
      elsif line.match(/^#{option}/)
        return line.gsub(/#{option}/,'')
      end  
    end  
  end
  return "Undefined"
end

$url = getOption("unset_presence_api=")


def log(text)
	$logger.info "Unset Presence: " + text
end

def unsetPresence(username)
  log("unsetPresence(#{username})")
  RestClient.post($url, :name => username)
  return true

  rescue RestClient::Exception
    log("RestClient::Exception with unsetPresence(#{username})")
end


log("Init Unset Presence Script")
unsetPresence(ARGV[0])


