require 'social_stream-base'
require 'paperclip'
require 'paperclip/social_stream-documents'
require 'paperclip-ffmpeg'
require 'delayed_paperclip'
require 'delayed_paperclip/social_stream-documents'
